### ISSUE TITLE
Issue with Active Nav Button

### ISSUE THREAD

**Issue by Aitzaz-Hakro** [angulardevelopment/handsontable#1]
![image](https://github.com/user-attachments/assets/67f46a89-46ba-4ece-adbd-5d6095329c33)

![image](https://github.com/user-attachments/assets/6da0adfe-d8fa-424a-b8ba-7faa7994dc40)

website is very attractive and cool but 
I found a minor issue, that user can not see, that, on which section he is currently active 

I think I can solve this issue using CSS 

what do you think, let me know.
do assign me thankyou.

**Comment by sunny7899** [comment]
Go ahead @AItzaz-hakro

**Comment by sunny7899** [comment]
any update on this @AItzaz-hakro

**Comment by AItzaz-hakro** [comment]
sorry for that 
I can't solve this issue 
I thoougt, it's just a simple html and css
but i feel this kind of tough 
thankyou

**Comment by Aitzaz-Hakro** [comment]
sorry for that
I can't solve this issue
I thoougt, it's just a simple html and css
but i feel this kind of tough
thankyou
